### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by stratigraphy** [robintrayler/modifiedBChron#3]
Dear Robin Trayler 

When installing modifiedBchron i get this warning message during installation:

Warning: C:/Users/Administrator/AppData/Local/Temp/RtmpieyM4E/R.INSTALL77b01e611ef0/modifiedBChron/man/ageModel.Rd:65: unexpected section header '\value'
Warning: C:/Users/Administrator/AppData/Local/Temp/RtmpieyM4E/R.INSTALL77b01e611ef0/modifiedBChron/man/ageModel.Rd:86: unexpected section header '\description'
Warning: C:/Users/Administrator/AppData/Local/Temp/RtmpieyM4E/R.INSTALL77b01e611ef0/modifiedBChron/man/ageModel.Rd:89: unexpected END_OF_INPUT '
'
Warning: C:/Users/Administrator/AppData/Local/Temp/RtmpieyM4E/R.INSTALL77b01e611ef0/modifiedBChron/man/bchron_model.Rd:53: unknown macro '\item'
Warning: C:/Users/Administrator/AppData/Local/Temp/RtmpieyM4E/R.INSTALL77b01e611ef0/modifiedBChron/man/bchron_model.Rd:55: unknown macro '\item'
Warning: C:/Users/Administrator/AppData/Local/Temp/RtmpieyM4E/R.INSTALL77b01e611ef0/modifiedBChron/man/bchron_model.Rd:57: unknown macro '\item'
Warning: C:/Users/Administrator/AppData/Local/Temp/RtmpieyM4E/R.INSTALL77b01e611ef0/modifiedBChron/man/bchron_model.Rd:59: unknown macro '\item'
Warning: C:/Users/Administrator/AppData/Local/Temp/RtmpieyM4E/R.INSTALL77b01e611ef0/modifiedBChron/man/bchron_model.Rd:61: unexpected section header '\value'
Warning: C:/Users/Administrator/AppData/Local/Temp/RtmpieyM4E/R.INSTALL77b01e611ef0/modifiedBChron/man/bchron_model.Rd:82: unexpected section header '\description'
Warning: C:/Users/Administrator/AppData/Local/Temp/RtmpieyM4E/R.INSTALL77b01e611ef0/modifiedBChron/man/bchron_model.Rd:85: unexpected END_OF_INPUT '
'
Warning: C:/Users/Administrator/AppData/Local/Temp/RtmpieyM4E/R.INSTALL77b01e611ef0/modifiedBChron/man/posteriorPlot.Rd:14: unknown macro '\item'
Warning: C:/Users/Administrator/AppData/Local/Temp/RtmpieyM4E/R.INSTALL77b01e611ef0/modifiedBChron/man/posteriorPlot.Rd:16: unexpected section header '\description'
Warning: C:/Users/Administrator/AppData/Local/Temp/RtmpieyM4E/R.INSTALL77b01e611ef0/modifiedBChron/man/posteriorPlot.Rd:19: unexpected END_OF_INPUT '

The result is an incomplete installation which does not allow me to run the functions with the errors. 

I've downloaded the package and investigated where the problem is. 
The problem is that you put a % sign in the description part of the functions:
ageModel.R
posteriorPlot.R
bchron_model.R 

The % sign  is seen as an operator, and as such, it throws an error message
I've replaced the % sign with "percent," and now it works.

So please implement this change to make the functions work again when downloading and installing your R package from Github.

Many thanks
Michiel

**Comment by robintrayler** [comment]
Hi Michiel, 

Can you provide an example of how you're installing the package? I've never had anyone else report a problem with the % symbols in the documentation. 

This code is how I usually advise folks to install. 

```
devtools::install_github('robintrayler/modifiedBchron')
```

Happy to make changes but I want to make sure it's a reproducible error first.

**Comment by stratigraphy** [comment]
Dear Robin Trayler,

I've tried to install your R pacakge in R studio on a 64bit windows 10 installation
So  when I install modifiedBchron via; devtools::install_github('robintrayler/modifiedBchron')

> devtools::install_github('robintrayler/modifiedBchron')

 Downloading GitHub repo robintrayler/modifiedBchron@HEAD ── R CMD build ─────────────────────────────────────────────────────────────────────────────────────────────── ✔  checking for file 'C:\Users\Administrator\AppData\Local\Temp\Rtmp4sxYxI\remotes3990b6a772f\robintrayler-modifiedBChron-10b8704/DESCRIPTION' ─  preparing 'modifiedBChron': ✔  checking DESCRIPTION meta-information ... ─  cleaning src    Warning: C:/Users/Administrator/AppData/Local/Temp/RtmpSYybI7/Rbuild10a067a64e8a/modifiedBChron/man/ageModel.Rd:65: unexpected section header '\value'    Warning: C:/Users/Administrator/AppData/Local/Temp/RtmpSYybI7/Rbuild10a067a64e8a/modifiedBChron/man/ageModel.Rd:86: unexpected section header '\description'    Warning: C:/Users/Administrator/AppData/Local/Temp/RtmpSYybI7/Rbuild10a067a64e8a/modifiedBChron/man/ageModel.Rd:89: unexpected END_OF_INPUT '    '    Warning: C:/Users/Administrator/AppData/Local/Temp/RtmpSYybI7/Rbuild10a067a64e8a/modifiedBChron/man/bchron_model.Rd:53: unknown macro '\item'    Warning: C:/Users/Administrator/AppData/Local/Temp/RtmpSYybI7/Rbuild10a067a64e8a/modifiedBChron/man/bchron_model.Rd:55: unknown macro '\item'    Warning: C:/Users/Administrator/AppData/Local/Temp/RtmpSYybI7/Rbuild10a067a64e8a/modifiedBChron/man/bchron_model.Rd:57: unknown macro '\item'    Warning: C:/Users/Administrator/AppData/Local/Temp/RtmpSYybI7/Rbuild10a067a64e8a/modifiedBChron/man/bchron_model.Rd:59: unknown macro '\item'    Warning: C:/Users/Administrator/AppData/Local/Temp/RtmpSYybI7/Rbuild10a067a64e8a/modifiedBChron/man/bchron_model.Rd:61: unexpected section header '\value'    Warning: C:/Users/Administrator/AppData/Local/Temp/RtmpSYybI7/Rbuild10a067a64e8a/modifiedBChron/man/bchron_model.Rd:82: unexpected section header '\description'    Warning: C:/Users/Administrator/AppData/Local/Temp/RtmpSYybI7/Rbuild10a067a64e8a/modifiedBChron/man/bchron_model.Rd:85: unexpected END_OF_INPUT '    '    Warning: C:/Users/Administrator/AppData/Local/Temp/RtmpSYybI7/Rbuild10a067a64e8a/modifiedBChron/man/posteriorPlot.Rd:14: unknown macro '\item'    Warning: C:/Users/Administrator/AppData/Local/Temp/RtmpSYybI7/Rbuild10a067a64e8a/modifiedBChron/man/posteriorPlot.Rd:16: unexpected section header '\description'    Warning: C:/Users/Administrator/AppData/Local/Temp/RtmpSYybI7/Rbuild10a067a64e8a/modifiedBChron/man/posteriorPlot.Rd:19: unexpected END_OF_INPUT '    ' ─  checking for LF line-endings in source and make files and shell scripts ─  checking for empty or unneeded directories ─  building 'modifiedBChron_0.7.0.tar.gz'     Installing package into ‘C:/Users/Administrator/AppData/Local/R/win-library/4.3’ (as ‘lib’ is unspecified) * installing *source* package 'modifiedBChron' ... ** using staged installation ** libs gcc  -I"C:/PROGRA~1/R/R-devel/include" -DNDEBUG     -I"C:/RBuildTools/4.2/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign  -c BchronModified.c -o BchronModified.o gcc -shared -s -static-libgcc -o modifiedBChron.dll tmp.def BchronModified.o -LC:/RBuildTools/4.2/x86_64-w64-mingw32.static.posix/lib/x64 -LC:/RBuildTools/4.2/x86_64-w64-mingw32.static.posix/lib -LC:/PROGRA~1/R/R-devel/bin/x64 -lR installing to C:/Users/Administrator/AppData/Local/R/win-library/4.3/00LOCK-modifiedBChron/00new/modifiedBChron/libs/x64 ** R ** data *** moving datasets to lazyload DB ** byte-compile and prepare package for lazy loading ** help Warning: C:/Users/Administrator/AppData/Local/Temp/RtmpCq9O52/R.INSTALL4480622549b5/modifiedBChron/man/ageModel.Rd:65: unexpected section header '\value' Warning: C:/Users/Administrator/AppData/Local/Temp/RtmpCq9O52/R.INSTALL4480622549b5/modifiedBChron/man/ageModel.Rd:86: unexpected section header '\description' Warning: C:/Users/Administrator/AppData/Local/Temp/RtmpCq9O52/R.INSTALL4480622549b5/modifiedBChron/man/ageModel.Rd:89: unexpected END_OF_INPUT ' ' Warning: C:/Users/Administrator/AppData/Local/Temp/RtmpCq9O52/R.INSTALL4480622549b5/modifiedBChron/man/bchron_model.Rd:53: unknown macro '\item' Warning: C:/Users/Administrator/AppData/Local/Temp/RtmpCq9O52/R.INSTALL4480622549b5/modifiedBChron/man/bchron_model.Rd:55: unknown macro '\item' Warning: C:/Users/Administrator/AppData/Local/Temp/RtmpCq9O52/R.INSTALL4480622549b5/modifiedBChron/man/bchron_model.Rd:57: unknown macro '\item' Warning: C:/Users/Administrator/AppData/Local/Temp/RtmpCq9O52/R.INSTALL4480622549b5/modifiedBChron/man/bchron_model.Rd:59: unknown macro '\item' Warning: C:/Users/Administrator/AppData/Local/Temp/RtmpCq9O52/R.INSTALL4480622549b5/modifiedBChron/man/bchron_model.Rd:61: unexpected section header '\value' Warning: C:/Users/Administrator/AppData/Local/Temp/RtmpCq9O52/R.INSTALL4480622549b5/modifiedBChron/man/bchron_model.Rd:82: unexpected section header '\description' Warning: C:/Users/Administrator/AppData/Local/Temp/RtmpCq9O52/R.INSTALL4480622549b5/modifiedBChron/man/bchron_model.Rd:85: unexpected END_OF_INPUT ' ' Warning: C:/Users/Administrator/AppData/Local/Temp/RtmpCq9O52/R.INSTALL4480622549b5/modifiedBChron/man/posteriorPlot.Rd:14: unknown macro '\item' Warning: C:/Users/Administrator/AppData/Local/Temp/RtmpCq9O52/R.INSTALL4480622549b5/modifiedBChron/man/posteriorPlot.Rd:16: unexpected section header '\description' Warning: C:/Users/Administrator/AppData/Local/Temp/RtmpCq9O52/R.INSTALL4480622549b5/modifiedBChron/man/posteriorPlot.Rd:19: unexpected END_OF_INPUT ' ' *** installing help indices ** building package indices ** testing if installed package can be loaded from temporary location ** testing if installed package can be loaded from final location ** testing if installed package keeps a record of temporary installation path * DONE (modifiedBChron)
--
 
I get the following output in the console

I hope this helps you out 
Greets,
Michiel

**Comment by robintrayler** [comment]
I'm unable to reproduce this issue on multiple computers so I'm going to close for now.
