### ISSUE TITLE
agePredict requires multiple stratigraphic horizons

### ISSUE THREAD

**Issue by Swanson-Hysell** [robintrayler/modifiedBChron#4]
I ran into an issue where it appears that agePredict cannot handle a single stratigraphic level.

This code:
```
Merced_age_predictions <- agePredict(model = Merced_age_model, 
                              newPositions = c(1460),
                              newPositionThicknesses = c(1))
```
gives the error
```
Error in apply(predictStore, 2, quantile, c((1 - probability)/2, 0.5,  : 
  dim(X) must have a positive length
```

While adding an additional value so that there were multiple new positions worked fine:
```
Merced_age_predictions <- agePredict(model = Merced_age_model, 
                              newPositions = c(800, 1460),
                              newPositionThicknesses = c(1, 1))
```
In this case, we only wanted to get age prediction at one horizon. This workaround is not a big deal, but I thought I would report the issue anyhow. 

Thanks for your work on this package! It is fun to be putting it to use.

**Comment by robintrayler** [comment]
Thanks for submitting an issue. I was missing a conversion to a `data.frame` in the code. I've just pushed and update that should fix the bug if you want to godhead and reinstall.
